[package]
name = "cardinality-estimator"
version = "1.0.0"
edition = "2021"
authors = ["Alex Bocharov <bocharov.alexandr@gmail.com>"]
description = "A crate for estimating the cardinality of distinct elements in a stream or dataset."
documentation = "https://docs.rs/cardinality-estimator"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/cloudflare/cardinality-estimator"
keywords = ["cardinality", "distinct-count", "hyperloglog", "probabilistic", "sketch"]
categories = ["algorithms", "data-structures"]

[dependencies]
serde = { version = "1.0.164", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.6.2", features = ["flamegraph", "protobuf", "criterion"] }
seahash = "4.1.0"
serde_json = "1.0.97"
test-case = "3.1.0"

[[bench]]
name = "cardinality_estimator_benchmark"
harness = false

[features]
default = []
with_serde = ["serde"]
